policyuniverse/__init__.py
The current implementation of `expand_policy` will both return the new expanded policy document, but since python is copy-by-reference it also mutates the input object.
Here we simply perform a deepcopy of the input object, before we start working on it.
=> Dont mutate the input data to expand_policy

policyuniverse/arn.py, setup.py
Add support for *.amazon.com service principals.
A few new service principals use *.amazon.com instead of *.amazonaws.com.  
Examples are:
alexa-appkit.amazon.com
alexa-connectedhome.amazon.com
alexa-appkit.amazon.com
The ARN class should be able to parse these service principals.
=> Support amazoncom service principal

policyuniverse/arn.py, policyuniverse/tests/test_arn.py
Some IAM resources like Managed Policies use "aws" as the account number:
> arn:aws:iam::aws:policy/AlexaForBusinessDeviceSetup
I've added it to the regex capture group (similar to how cloudfront is whitelisted)
=> Added 'aws' to regex account_number group

policyuniverse/statement.py, policyuniverse/tests/test_statement.py
Fixing Issue #15. Condition blocks using ForAny/ForAll must be a list or they are invalid
=> Fixing Issue #15. Condition blocks using ForAny/ForAll must be a list or they are invalid

README.md, policyuniverse/action_categories.py, policyuniverse/data.json, policyuniverse/tests/test_action_categories.py, policyuniverse/tests/test_policy.py, setup.py
```
@>>> from policyuniverse.action_categories import actions_for_category
@>>> actions = actions_for_category('Tagging')
@>>> len(actions)
180
```
```
@>>> for a in actions:
@...     print(a)
@... 
ecs:tagresource
cloudwatch:untagresource
iam:untagrole
resource-groups:creategroup
acm-pca:untagcertificateauthority
license-manager:untagresource
datapipeline:addtags
appstream:tagresource
events:tagresource
ssm:addtagstoresource
autoscaling:createorupdatetags
es:addtags
servicecatalog:copyproduct
sagemaker:addtags
events:putrule
elasticache:removetagsfromresource
discovery:createtags
cloudfront:createdistributionwithtags
states:tagresource
mobiletargeting:tagresource
clouddirectory:tagresource
rds:createdbsnapshot
elasticache:addtagstoresource
sagemaker:deletetags
mediaconvert:tagresource …
```
=> Adding new Tagging AWS category

policyuniverse/action_categories.py, policyuniverse/statement.py, policyuniverse/tests/test_action_categories.py
Adding `quicksight:describecustompermissions` to the list of actions that seem to be categorized as WRITE actions even though they begin with `Describe`.
Should fix all unit tests.
=> Adding new miscategorized AWS action to unit tests.

.github/workflows/pythonpackage.yml, README.md, updater/awsconsole.js, updater/updater.py
Hello - we ran into issue of ELB v1 actions are not recognized by policyuniverse. We did analyses it turns out be ELB v1 and v2 uses the same service name which is getting overwritten in the action generation process - `data.json`.
Credit goes to @ksenthilmurugan, he identified and able to address this issue.
Kindly review and merge this PR. So that we take the latest pip lib version after publish. Thanks.
Feel free to improve it as you see fit.
=> Addressing the missing actions for same service names e.g. ELB

setup.py
I am trying to import this package into an internal repository using an internal procurement process and it is failing to find the license, I would like to add this additional license metadata to the python package to see if that will help.
Also, I did not find release instructions, could you help me process this change for release to the PyPI repository?
Thanks!
=> Add license metadata to python package declaration

policyuniverse/tests/test_action_categories.py
$python -m pytest
============================= test session starts ==============================
platform linux -- Python 3.9.1, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/bardon/workspace/fork_space/policyuniverse
collected 32 items                                                             
policyuniverse/tests/test_action_categories.py ..                        [  6%]
policyuniverse/tests/test_arn.py ..                                      [ 12%]
policyuniverse/tests/test_expander_minimizer.py ............             [ 50%]
policyuniverse/tests/test_policy.py .......                              [ 71%]
policyuniverse/tests/test_statement.py ......                            [ 90%]
updater/test_service.py .                                                [ 93%] …
=> Update the list of miscategorized actions in the unit tests - fixes Netflix-Skunkworks/policyuniverse#86

policyuniverse/expander_minimizer.py, setup.py
This PR optimizes a hot path in the action wildcard expansion flow. The `_expand_wildcard_action()` function now maps a new `_expand()` function over the list of actions. For the `_expand()` function, I opted to use `fnmatch.filter()` instead of `fnmatch.fnmatchcase()` for a pretty significant performance improvement.
The `_expand_wildcard_action()` has a _really_ ugly list comprehension to flatten a list of lists. It's basically impossible to read, but there's another significant performance improvement with this change. StackOverflow reference for the ugly part: https://stackoverflow.com/a/952952
With some quick profiling, the changes in this PR decreased the time Repokid spent in this codepath from 30 seconds to 10 seconds for a collection of ~100 roles.
=> Optimize action expansion logic

policyuniverse/common.py, policyuniverse/expander_minimizer.py, policyuniverse/policy.py, policyuniverse/statement.py, policyuniverse/tests/test_common.py, policyuniverse/tests/test_expander_minimizer.py, policyuniverse/tests/test_policy.py
=> Allow all array Sequence sub-classes to be used in policy documents

policyuniverse/statement.py, policyuniverse/tests/helpers.py, policyuniverse/tests/test_policy.py, policyuniverse/tests/test_statement.py
Continues work from #94.
Closes #98.
=> Expand type checking to any Mapping sub-class for Principals

policyuniverse/statement.py, policyuniverse/tests/test_statement.py
I noticed what I think is a bug in the _condition_entries() function within statement.py (lines 210-215), which states:
```
```
...before tossing out any ForAny/ForAll values which aren't a list. I'm not sure why this is here - it seems it was true previously, since someone made a note of it and tests to confirm - but when testing it seems that ForAny/ForAll operators which correspond to a single value (not in a list) are now interpreted correctly. For example, testing SNS subscriptions to a queue with the following access policy configured:
```
{
"Version": "2012-10-17",
"Id": "default",
"Statement": [
{
"Sid": "default",
"Effect": "Allow",
"Principal": {
"AWS": "*"
},
"Action": "SQS:*",
"Resource": "arn:aws:sqs:us-west-2:<account_id_1>:policyuniverse-test-queue",
"Condition": { …
```
=> Do not ignore ForAny/ForAll set operators when they don't have lists

.github/workflows/pythonpackage.yml, policyuniverse/statement.py, policyuniverse/tests/test_statement.py
Addresses #102, but does not differentiate PrincipalARNs internally from ARNs. This is different from the solution I posted in that issue, as I noted that `KMS:CallerAccount`, `AWS:SourceAccount`, and `AWS:SourceOwner` use the same internal representation, and are not returned separately by the `condition_accounts` property.
In addition, a test case has been added to verify that the PrincipalARN is identified correctly, and that statements which use an appropriately-restrictive PrincipalARN are not mislabeled as publicly accessible.
=> Add support for aws:PrincipalARN in statement conditions

.github/workflows/pythonpackage.yml
Uploading coverage reports fails from a fork due to the unavailability of secrets. This PR adds more conditions to the coverage upload step so it gets skipped on PRs from forks.
=> Skip coverage upload on PR from fork

.github/workflows/pythonpackage.yml, .github/workflows/updater.yml, updater/updater.py
This PR fixes the automatic updater action (most of the time, at least) by explicitly installing the most recent LTS version of NodeJS. I also fixed the coverage upload failures for PRs.
=> Add NodeJS setup step to Updater action

policyuniverse/statement.py, policyuniverse/tests/test_statement.py, setup.py
Hey all! Quick PR today, just to add the `AWS:PrincipalAccount` key ([ref](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-principalaccount)) for use in Conditions statements - a one-line change to support it, and 21 more (including empty lines) to ensure it's tested.
I did not bump the version as I saw there was work going on today, so if you'll take the PR, please update the version number. Cheers!
=> Add support for AWS:PrincipalAccount key

policyuniverse/tests/test_action_categories.py
This fixes a test that started failing after today's SDF update.
=> Add test exception for bugbust:getjoineventstatus

policyuniverse/organization.py, policyuniverse/statement.py, policyuniverse/tests/test_organization.py, policyuniverse/tests/test_policy.py, policyuniverse/tests/test_statement.py
Resolves #106 
This is a larger PR and might take some reviewing to grok, but I'll include the highlights.
This PR adds:
* policyuniverse/organization.py
* policyuniverse/tests/test_organization.py
These parse and dissect Organization-related content, so far it supports taking in Organization IDs (from `aws:PrincipalOrgID` conditions) and Organization Paths (from `aws:PrincipalOrgPaths` conditions), storing them in a new Organization() object which is similar to how Policy Universe handles ARNs.
The core reference material for the implemented logic is from reading:
* https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-principalorgpaths
* https://aws.amazon.com/blogs/security/iam-share-aws-resources-groups-aws-accounts-aws-organizations/ …
=> Adds PrincipalOrgPath support via new organization.py

policyuniverse/__init__.py, policyuniverse/arn.py, policyuniverse/organization.py, policyuniverse/statement.py, policyuniverse/tests/__init__.py
Logging configuration should be left to the applications. Running [`logging.basicConfig`](https://docs.python.org/3/library/logging.html#logging.basicConfig) twice has no effect and this could prove problematic for an application, since if it imports `policyuniverse` first the logging configuration would already have been set.
In addition, downgrading warning logs to debug level also makes sense for a library, since warning-level logs can be captured by error collection SDKs such as [Sentry](https://github.com/getsentry/sentry-python) or trigger alerting based on log filtering.
Closes https://github.com/Netflix-Skunkworks/policyuniverse/issues/34
=> Remove logging configuration and downgrade to debug level

policyuniverse/statement.py, policyuniverse/tests/test_statement.py
This PR switches the userid check to use `find()` instead of `index()`, the latter of which raises a `ValueError` if the substring is not found.
One notable behavior is that a zero-length string as an input to `_userid_internet_accessible()` returns `False`. The only way to get here would be to analyze an invalid policy, so I don't see much value in handling this edge case more explicitly.
Fixes #146
=> Fix: Handle edge case in userid internet accessibility check

.github/workflows/pythonpackage.yml, .pre-commit-config.yaml, policyuniverse/tests/test_action_categories.py, policyuniverse/tests/test_expander_minimizer.py, setup.py
Python 3.6 hit [EOL in December 2021](https://endoflife.date/python). Something was broken in the Python 3.6 build, so the easiest solution was to remove it.
This also makes some other changes to unbreak the build process.
=> Drop support for Python 3.6, update pre-commit revs to fix build

updater/awsconsole.js
With this change I was able to run the updater on WSLv2 - guessing it should now work in Github Actions as well.
I noticed when I browsed to the old `iam_url` in chrome and opened the inspector, I couldn't interactively find the CSRF token at either of the two locations (`app.orcaCsrf.token` or `window.Csrf.fromCookie(null)`). So I changed it to a URL for building an inline IAM policy and suddenly a few things happened.
1) I could pull the CSRF token from the Chrome inspector.
2) When running the phantom code interactively, the callback on the `page.includeJs` started working. (Before it would print `Successfully logged in` and then just stop.
```
console.log('Successfully logged in')
page.includeJs(
"https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js",
function() { …
```
=> The CSRF token was unavailable with the previous `iam_url`.
